name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT }}
        token: ${{ secrets.BOT_TOKEN }}
        args: The ${{ github.event_name }} event triggered first step.
