name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      env:
        GITHUB_TAG: ${{ steps.vars.outputs.tag }}
      with:
        to: ${{ secrets.CHAT }}
        token: ${{ secrets.BOT_TOKEN }}
        message: |
          Helmwave v${GITHUB_TAG} is ready!
          See more: https://github.com/zhilyaev/helmwave/releases/tag/${GITHUB_TAG}
