name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT }}
        token: ${{ secrets.BOT_TOKEN }}
        message: |
          Helmwave v${{ github.ref }} is ready!
          See more: https://github.com/zhilyaev/helmwave/releases/tag/${{ github.ref }}
